Fixed sporadic StaleElementReferenceExcepton
org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
        at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:122)
        at geb.navigator.NonEmptyNavigator.matches_closure30(NonEmptyNavigator.groovy:525)
        at geb.navigator.NonEmptyNavigator.matches(NonEmptyNavigator.groovy:520)
        at geb.navigator.NonEmptyNavigator.filter_closure2(NonEmptyNavigator.groovy:65)
        at geb.navigator.NonEmptyNavigator.filter(NonEmptyNavigator.groovy:65)
        at geb.navigator.NonEmptyNavigator.find(NonEmptyNavigator.groovy:50)
        at geb.content.NavigableSupport.$(NavigableSupport.groovy:96)
        at geb.content.PageContentTemplateFactoryDelegate.methodMissing(PageContentTemplateFactoryDelegate.groovy:34)
        at com.sonatype.insight.brain.testing.functional.modules.PolicyEditorModule._clinit__closure3_closure15(PolicyModule.groovy:49)
        at com.sonatype.insight.brain.testing.functional.modules.PolicyEditorModule._clinit__closure3_closure15(PolicyModule.groovy)
        at geb.content.PageContentTemplate.invokeFactory(PageContentTemplate.groovy:97)
        at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy:59)
        at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy)
        at geb.content.PageContentTemplate.create(PageContentTemplate.groovy:82)
        at geb.content.PageContentTemplate.get(PageContentTemplate.groovy:54)
        at geb.content.NavigableSupport.getContent(NavigableSupport.groovy:45)
        at geb.content.NavigableSupport.propertyMissing(NavigableSupport.groovy:129)
        at com.sonatype.insight.brain.testing.functional.PolicyTagSpec.Initially a policy applies to all applications_closure3(PolicyTagSpec.groovy:50)